import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import HeaderTop from "./HeaderComponent/headertop";
import Footer from "./FooterComponent/footer";

const roboto = Roboto({
  variable: "--font-roboto", // Đổi thành tên hợp lý
  subsets: ["latin"],
  weight: ["400", "700"], // Tuỳ chỉnh trọng lượng (nếu cần)
});

export const metadata: Metadata = {
  title: "Trang chủ - Thời trang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <HeaderTop />
        <main className="">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
